### ISSUE TITLE
docker-compose doesn't work

### ISSUE THREAD

**Issue by envil** [gdi2290/angular-starter#2026]
* **I'm submitting a ...**
[ x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
Cannot `docker-compose up`:

> Starting afd757f3786e_angular-starter ... done
> Attaching to afd757f3786e_angular-starter

And it hangs there

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
Clone the image:

`git clone --depth 1 https://github.com/gdi2290/angular-starter.git`
`cd ./angular-starter/`

Build the image:
`npm install`
`docker-compose build`

Up the image:
`docker-compose up`

* **What is the expected behavior?**
The `docker-compose up` command should invoke the webpack dev-server to serve.

* **Please tell us about your environment:**

- Angular version: 6.0.9
- Browser: [all ]
- OS: macOs 10.11.6

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I think there should be a command in the `docker-compose.yml` file:

```
version: '3'
services:
  angular-starter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-starter
    networks:
      - angular-starter
    ports:
      - '8080:80'
    command: npm run start:hmr
networks:
  angular-starter:
    driver: bridge
```

So I added it then it threw this:

> ERROR: for angular-startger  Cannot start service pretradeb2c: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"npm\": executable file not found in $PATH": unknown

I think the cause of this error is because of the multi-stage docker building defined in the Dockerfile, since node image had been removed, that's why there're no npm in the new nginx.
